//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ScoolMGT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int Id { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<int> FessType { get; set; }
        public string Fess { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedBy { get; set; }
    }
}
