//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ScoolMGT
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstsiteaction
    {
        public int SiteActionID { get; set; }
        public string SiteActionName { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<int> ParentSiteActionID { get; set; }
        public string URL { get; set; }
        public int Sequence { get; set; }
        public string PageHelp { get; set; }
        public int SiteActionType { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
